version: '3'

services:
  influxsrv:
      image: registry.docker-cn.com/tutum/influxdb:0.8.8-staging
      ports:
          - "8083:8083"
          - "8086:8086"
      expose:
          - "8086"
          - "8090"
          - "8099"
      environment:
          - PRE_CREATE_DB=cadvisor
      deploy:
        replicas: 1

  cadvisor:
      image: registry.docker-cn.com/google/cadvisor:latest
      command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
      ports:
          - "8080:8080"
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker:/var/lib/docker:ro
      links:
          - influxsrv:influxsrv
      deploy:
        replicas: 2

  tasseo:
      image: registry.int.mimikko.cn/rtasseo:latest
      ports:
          - "5000:5000"
      links:
          - influxsrv:influxsrv
      environment:
          - INFLUXDB_URL=http://influxsrv:8086/db/cadvisor
          - INFLUXDB_AUTH=root:root
      deploy:
        replicas: 1

networks:
  redis:
    external: true
