version: '3'

services:
  tasseo:
      image: registry.int.mimikko.cn/tasseo:latest
      ports:
          - "9000:5000"
      environment:
          - INFLUXDB_URL=http://http://42.159.144.148:9001/db/cadvisor
          - INFLUXDB_AUTH=root:root
          - "com.mimikko.environment=c1"
      deploy:
        replicas: 1
      networks:
        - redis

  influxsrv:
      image: registry.docker-cn.com/tutum/influxdb:0.8.8
      hostname: influxdb
      ports:
          - "8083:8083"
          - "9001:8086"
      environment:
          - PRE_CREATE_DB=cadvisor
          - "com.mimikko.environment=c1"
      deploy:
        replicas: 1
      networks:
      - redis

  cadvisor:
      image: registry.docker-cn.com/google/cadvisor:latest
      command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
      ports:
          - "8080:8080"
      volumes:
          - /:/rootfs:ro
          - /var/run:/var/run:rw
          - /sys:/sys:ro
          - /var/lib/docker:/var/lib/docker:ro
      deploy:
        replicas: 2
      networks:
        - redis

networks:
  redis:
    external: true
